apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: mypassword
  POSTGRES_HOST: database-1.cu89b3f2cbki.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: arn:aws:s3:::awsbucketproject3
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: testing
  URL: http://localhost:8100
